### ISSUE TITLE
Add "Zipcode field and button" to Main Activity

### ISSUE THREAD

**Issue by kpf5297** [NittanyLions42/wellnessbuddy#18]
## Task description

Add "Zipcode field and button" to Main Activity 

## Detailed Steps

- [ ] Update sequence diagram
- [ ] Update use case(s) text
- [ ] Update use case(s) diagram
- [ ] Update graphic for document

## Relate to issue(s)

/relate subtask-of [[Epic]: GUI: Main Activity Page#11](https://github.com/NittanyLions42/wellnessbuddy/issues/11)

Fixes {link for the pull request}
