### ISSUE TITLE
Initial Dependencies for Android project

### ISSUE THREAD

**Issue by kpf5297** [NittanyLions42/wellnessbuddy#19]
## Task description

Setting up our Android project to leverage specific libraries.

The activity-ktx artifact includes Kotlin extensions for the AndroidX Activity library. Kotlin extensions provide concise and idiomatic ways to interact with the Android framework using the Kotlin programming language.

The Lifecycle library provides classes and interfaces to manage the lifecycle of Android components, such as activities and fragments. It helps in handling the lifecycle events of these components, allowing developers to write code that reacts to changes in the lifecycle state.

## Detailed Steps

- [x] ... Add lifecycle component dependency 'activity-ktx'
- [x] ... Add lifecycle management dependency  'lifecycle-runtime-ktx'
- [x] Set view binding in main activity

## Relate to issue(s)

/relate subtask-of {github.com/NittanyLions42/repository-name#issue-number}
Fixes {link for the pull request}

**Comment by kpf5297** [comment]
Implemented
