### ISSUE TITLE
Add Theme Elements from Task #16 and 18 outputs

### ISSUE THREAD

**Issue by kpf5297** [NittanyLions42/wellnessbuddy#20]
## Task description

Add Theme Elements from Task #16 and 18 outputs

## Detailed Steps

- [x] Add colors to xml
- [x] Add theme to xml
- [x] Verify [Excel File with Color choices and Hex values](https://pennstateoffice365.sharepoint.com/:x:/r/sites/WellnessBuddy/Shared%20Documents/General/Weekly%20Team%20Assignments/GUI%20Elements/GUI%20Element%20Tables.xlsx?d=w2728d48831b842a7a1a700893ced768d&csf=1&web=1&e=4wNdEl)

## Relate to issue(s)

/relate subtask-of {github.com/NittanyLions42/repository-name#issue-number}
Fixes {link for the pull request}

**Comment by kpf5297** [comment]
All tasks complete.
