### ISSUE TITLE
Add Weather Card to main activity

### ISSUE THREAD

**Issue by kpf5297** [NittanyLions42/wellnessbuddy#22]
## Task description

Add the weather card and its subcomponents including the zipcode input.

## Detailed Steps

- [x] Add forecast card title
- [x] Add card for forecast
- [x] Add zip code entry and button
- [x] Add location output
- [x] Add date output
- [x] Add temp output
- [x] Add weather icon imageview
- [x] Add sunrise label and time
- [x] Add precip. label and time
- [x] Add sunset label and time

## Relate to issue(s)

Fixes {link for the pull request}

/relate subtask-of [[Epic]: GUI: Main Activity Page#11](https://github.com/NittanyLions42/wellnessbuddy/issues/11)

**Comment by kpf5297** [comment]
work complete.
