### ISSUE TITLE
Add Recommended Activity Card to main activity

### ISSUE THREAD

**Issue by kpf5297** [NittanyLions42/wellnessbuddy#23]
## Task description

Add Recommended Activity Card to main activity.

## Detailed Steps

- [x] Add the recommended activity card title "Recommended Activity"
- [x] Add the recommended activity card
- [x] Add the recommended activity title (i.e. "Touch Some Grass")
- [x] Add the recommended activity imageView 
- [x] Add the recommended activity description text area
- [x] Add "Generate Random Activity" button

## Relate to issue(s)

/relate subtask-of [[Epic]: GUI: Main Activity Page#11](https://github.com/NittanyLions42/wellnessbuddy/issues/11)

Fixes {link for the pull request}
