### ISSUE TITLE
Add side-scrolling forecast

### ISSUE THREAD

**Issue by kpf5297** [NittanyLions42/wellnessbuddy#26]
## Task description

Add the ability to scroll through five separate forecast cards.

## Detailed Steps

- [x] Add scrollview to mainactivity
- [x] Create 5 separate forecast cards and add to scrollview
- [x] Add spacing for best view of scrolling weather

## Relate to issue(s)

/relate subtask-of [[Epic]: GUI: Main Activity Page#11](https://github.com/NittanyLions42/wellnessbuddy/issues/11)
Fixes {link for the pull request}
