### ISSUE TITLE
Add Internet Access to the app

### ISSUE THREAD

**Issue by emilyyankan** [NittanyLions42/wellnessbuddy#35]
## Task description
This task is to add internet access to the App. To perform network operations in our application, the manifest file `AndroidManifest.xml` must include the following permissions: 
`<uses-permission android:name="android.permission.INTERNET" />`  to enable HTTP request. In addition, Coroutine dependencies will also be needed for providing a more efficient and manageable way of handling asynchronous tasks and concurrency, especially for `Retrofit`.

[AndroidDeveloperGuide](https://developer.android.com/develop/connectivity/network-ops/connecting)

## Detailed Steps
- [ ] Update `build.gradle` with dependency needed
- [ ] Update `AndroidManifest.xml` 
- [ ] test the app with internet access (hold until first API call code is completed)

## Relate to issue(s)

/relate subtask-of {github.com/NittanyLions42/repository-name#issue-number}
Fixes {link for the pull request}
