### ISSUE TITLE
DEMO - Set up Authentication

### ISSUE THREAD

**Issue by emilyyankan** [NittanyLions42/wellnessbuddy#4]
## Task description
We will set up the authentication logic in this task for the user account piece of the project.

## Detailed Steps

- [ ] Implement logic for user registration functionality in Java/Kotlin.
- [ ] Create a database schema to store user account information.
- [ ] Implement user login functionality.

## Relate to issue(s)

/relate subtask-of https://github.com/NittanyLions42/wellnessbuddy/issues/3
Fixes https://github.com/NittanyLions42/wellnessbuddy/issues/4
